services:
  api:
    build:
      context: ./          # The working directory for Docker
      dockerfile: ./api/Dockerfile  # Optional if file is just 'Dockerfile'
    restart: always
    image: ce-api-image
    ports:
      - "7878:8000"
    environment:
      - SSL_KEYFILE=${SSL_KEYFILE}
      - SSL_CERTFILE=${SSL_CERTFILE}
    volumes:
      - ./core:/app/core  # Needed since Dockerfile references /core
      - ./api:/app/api
      - ./api.py:/app/api.py
      - ./favicon.ico:/app/favicon.ico
    working_dir: /app
    #command: uvicorn api:app --host 0.0.0.0 --port 8000 --ssl-keyfile ${SSL_KEYFILE} --ssl-certfile ${SSL_CERTFILE}
    command: uvicorn api:app --host 0.0.0.0 --port 8000